---
#
# Project:: Ansible Role - Linux Users
#
# Copyright 2020, Route 1337, LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Manage user accounts and sudo privileges across Linux servers

- name: Set distribution specific variables
  include_vars: '{{ item }}'
  with_first_found:
    - '{{ ansible_distribution }}.yml'
- import_tasks: prereqs.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
- import_tasks: root.yml
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'CentOS'
- import_tasks: users.yml
  when: (ansible_distribution == 'Ubuntu' and linux_users.users is defined) or (ansible_distribution == 'CentOS' and linux_users.users is defined)
- import_tasks: user_cleanup.yml
  when: (ansible_distribution == 'Ubuntu' and linux_users.users is defined) or (ansible_distribution == 'CentOS' and linux_users.users is defined)
