---
#
# Project:: Ansible Role - Linux Users
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Configure the prerequisites for user management

- name: Refresh apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install the zsh package
  ansible.builtin.apt:
    name: zsh
    state: present

- name: Create an admin group for password-less sudo options
  ansible.builtin.group:
    gid: 1337
    name: sysadmins
    state: present

- name: Create a group for non-admins
  ansible.builtin.group:
    gid: 8737
    name: sysusers
    state: present

- name: Create a group for service accounts (password-less sudo)
  ansible.builtin.group:
    gid: 7782
    name: svcaccounts
    state: present

- name: Set sysadmins to have password-less sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^[%]sysadmins'
    line: '%sysadmins ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Set svcaccounts to have password-less sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^[%]svcaccounts'
    line: '%svcaccounts ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'
