---
#
# Project:: Ansible Role - Linux Users
#
# Copyright 2020, Route 1337 LLC, All Rights Reserved.
#
# Maintainers:
# - Matthew Ahrenstein: matthew@route1337.com
#
# See LICENSE
#

# Delete and cleanup after users in /home/ that aren't on one of the 3 groups
# created by this role

- name: Find home directories in /home/
  ansible.builtin.find:
    paths: /home
    file_type: directory
    recurse: false
  register: home_dirs

- name: Delete unmanaged users
  ansible.builtin.user:
    name: '{{ item }}'
    state: absent
    remove: true
  loop: "{{ home_dirs.files | map(attribute='path') | map('basename') | list }}"
  when: item not in linux_users.users | map(attribute='username') | list
